/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 laptop.glb 
Author: Gin Kern Creative Cloud (https://sketchfab.com/GinKern)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-2021-abec08722a504f7dbc1f76cd78201f3e
Title: Macbook Pro 2021
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/laptop.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.121, 0.007, 0]}>
        <mesh geometry={nodes.Object_11.geometry} material={materials.MacBookPro} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.MacBookPro} />
      </group>
      <mesh geometry={nodes.Object_8.geometry} material={materials.MacBookPro} />
    </group>
  )
}

useGLTF.preload('/laptop.glb')
